# Generated by Django 5.1.4 on 2025-03-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_app', '0002_approval_leave_attendance_approval_shift_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='shift_day',
            field=models.CharField(choices=[('working_day', 'วันทำงาน'), ('day_off', 'วันหยุดของพนักงาน'), ('public_holiday', 'วันหยุดนักขัตฤกษ์')], default='working', max_length=50),
        ),
    ]
