# Generated by Django 5.1.4 on 2025-03-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_app', '0004_alter_approval_approval_type_alter_approval_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='shift_day',
            field=models.CharField(blank=True, choices=[('working_day', 'วันทำงาน'), ('day_off', 'วันหยุดของพนักงาน'), ('public_holiday', 'วันหยุดนักขัตฤกษ์')], default='working', max_length=50, null=True),
        ),
    ]
