# Generated by Django 5.1.4 on 2025-03-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_app', '0005_alter_approval_shift_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='shift_day',
            field=models.CharField(blank=True, choices=[('working_day', 'วันทำงาน'), ('day_off', 'วันหยุดของพนักงาน'), ('public_holiday', 'วันหยุดนักขัตฤกษ์')], max_length=50, null=True),
        ),
    ]
