# Generated by Django 5.1.4 on 2025-03-18 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_app', '0006_alter_approval_shift_day'),
        ('attendance_app', '0010_talog_edittimeattendance'),
        ('branch_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='branch_app.bsnbranch'),
        ),
        migrations.AddField(
            model_name='approval',
            name='edit_time_attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='edit_time_attendance_id', to='attendance_app.edittimeattendance'),
        ),
        migrations.AddField(
            model_name='approval',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='approval_type',
            field=models.CharField(blank=True, choices=[('leave', 'ขอลา'), ('shift', 'เปลี่ยนกะทำงาน'), ('edit_time', 'แก้ไขเวลางาน')], max_length=10, null=True),
        ),
    ]
