# Generated by Django 5.1.4 on 2025-03-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_app', '0007_approval_branch_approval_edit_time_attendance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='timestamp',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
