# Generated by Django 5.1.4 on 2025-01-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveattendance',
            name='type',
            field=models.CharField(choices=[('sick_leave', 'ลาป่วย'), ('annual_leave', 'ลาพักร้อน'), ('absence_leave', 'ลากิจ'), ('maternity_leave', 'ลาคลอด'), ('bereavement_leave', 'ลาไปงานศพ')], default='sick_leave', max_length=50),
        ),
    ]
