# Generated by Django 5.1.4 on 2025-01-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0002_leavetype_remove_leaveattendance_type_leavebalance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveattendance',
            name='status',
            field=models.CharField(choices=[('approved', 'อนุมัติ'), ('pending', 'รออนุมัติ'), ('rejected', 'ปฏิเสธ'), ('cancelled', 'ยกเลิก')], default='pending', max_length=50),
        ),
    ]
