# Generated by Django 5.1.4 on 2025-02-07 09:53

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0002_leaveattendance_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('morning_start', models.TimeField(default=datetime.time(9, 0))),
                ('morning_end', models.TimeField(default=datetime.time(13, 0))),
                ('afternoon_start', models.TimeField(default=datetime.time(14, 0))),
                ('afternoon_end', models.TimeField(default=datetime.time(18, 0))),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='leave_balances', to='attendance_app.leavetype'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='leave_balances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leavebalanceinitial',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='leave_balances_initial', to='attendance_app.leavetype'),
        ),
        migrations.CreateModel(
            name='ShiftSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('availability', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shift_schedules', to='attendance_app.shift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shift_schedules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
