# Generated by Django 5.1.4 on 2025-01-16 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0004_leaveattendance_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavebalance',
            old_name='remaining_days',
            new_name='remaining_hours',
        ),
        migrations.RenameField(
            model_name='leavebalance',
            old_name='total_days',
            new_name='total_hours',
        ),
        migrations.RemoveField(
            model_name='leaveattendance',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='leaveattendance',
            name='start_date',
        ),
        migrations.AddField(
            model_name='leaveattendance',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='leaveattendance',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
