# Generated by Django 5.1.4 on 2025-02-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0004_approval_publicholiday_delete_dayoff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftschedule',
            name='time_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shiftschedule',
            name='time_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
