# Generated by Django 5.1.4 on 2025-01-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0005_rename_remaining_days_leavebalance_remaining_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveattendance',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveattendance',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
