# Generated by Django 5.1.4 on 2025-01-17 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0006_alter_leaveattendance_end_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalanceInitial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_code', models.CharField(blank=True, max_length=128, null=True)),
                ('total_hours', models.FloatField(default=0)),
                ('remaining_hours', models.FloatField(default=0)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances_initial', to='attendance_app.leavetype')),
            ],
        ),
    ]
