# Generated by Django 5.1.4 on 2025-02-19 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0006_remove_shiftschedule_time_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftschedule',
            name='approve_user',
        ),
        migrations.RemoveField(
            model_name='shiftschedule',
            name='status',
        ),
        migrations.AddField(
            model_name='leaveattendance',
            name='approval',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='leave_approval', to='attendance_app.approval'),
        ),
        migrations.AddField(
            model_name='shiftschedule',
            name='approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shift_approval', to='attendance_app.approval'),
        ),
        migrations.AddField(
            model_name='shiftschedule',
            name='time_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftschedule',
            name='time_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
