# Generated by Django 5.1.4 on 2025-03-18 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0009_remove_leaveattendance_approval_and_more'),
        ('branch_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaLog',
            fields=[
                ('ta_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('staff_id', models.BigIntegerField(blank=True, null=True)),
                ('do_staff_id', models.IntegerField(blank=True, null=True)),
                ('qr_code', models.CharField(blank=True, max_length=254, null=True)),
                ('rec_key', models.CharField(blank=True, max_length=254, null=True)),
                ('brc_id', models.BigIntegerField(blank=True, null=True)),
                ('gps_lat', models.CharField(blank=True, max_length=254, null=True)),
                ('gps_lng', models.CharField(blank=True, max_length=254, null=True)),
                ('staff_photo', models.CharField(blank=True, max_length=254, null=True)),
                ('log_timestamp', models.DateTimeField(blank=True, null=True)),
                ('device_no', models.CharField(blank=True, max_length=254, null=True)),
                ('http_user_agent', models.CharField(blank=True, max_length=254, null=True)),
                ('remote_addr', models.CharField(blank=True, max_length=254, null=True)),
                ('log_status', models.CharField(blank=True, max_length=254, null=True)),
                ('approve_staff_id', models.BigIntegerField(blank=True, null=True)),
                ('date_of_approve', models.DateTimeField(blank=True, null=True)),
                ('insert_usr_id', models.BigIntegerField(blank=True, null=True)),
                ('date_of_insert', models.DateTimeField(blank=True, null=True)),
                ('update_usr_id', models.BigIntegerField(blank=True, null=True)),
                ('date_of_update', models.DateTimeField(blank=True, null=True)),
                ('delete_usr_id', models.BigIntegerField(blank=True, null=True)),
                ('date_of_delete', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ta_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EditTimeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('approved', 'อนุมัติ'), ('pending', 'รออนุมัติ'), ('rejected', 'ปฏิเสธ'), ('cancelled', 'ยกเลิก')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('approve_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='edit_time_attendance_approve_user', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='edit_time_attendance', to='branch_app.bsnbranch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='edit_time_attendance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
