# Generated by Django 5.1.4 on 2025-03-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0010_talog_edittimeattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edittimeattendance',
            name='timestamp',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
