# Generated by Django 5.1.4 on 2025-01-21 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_app', '0001_initial'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bsnstaff',
            name='brc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk_bsnbranch', to='branch_app.bsnbranch'),
        ),
    ]
