# Generated by Django 5.1.4 on 2025-01-02 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsnstaff',
            name='django_usr_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='django_usr_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
