# Generated by Django 5.1.4 on 2025-02-07 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_app', '0003_user_nick_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsnstaff',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='group', to='auth.group'),
        ),
    ]
